FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# On copie tout le dossier api dans le conteneur
COPY api/ ./api/

# On s'assure que Python considère les dossiers comme des packages
RUN touch ./api/__init__.py
RUN touch ./api/app/__init__.py

ENV PYTHONPATH=/app:/app/api

# LA MODIFICATION EST ICI : on pointe vers api.app.main
CMD ["uvicorn", "api.app.main:app", "--host", "0.0.0.0", "--port", "8000"]