
[pytest]
DJANGO_SETTINGS_MODULE = django_political_app.settings
python_files = tests.py test.py test_*.py *_test.py
python_classes = Test*
python_functions = test_*
testpaths = django_political_app api
pythonpath = django_political_app api
env =
    SECRET_KEY=test-secret-key-not-for-production-only-for-tests
    DEBUG=True
    DATABASE_URL=sqlite:///./test.db
 